on:
    workflow_call:
    push:
        branches:
            [main]
    pull_request:
        branches:
            [main]

jobs:
    test:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                package: [dotagrid-cli, dota-hero-grid]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - uses: dtolnay/rust-toolchain@stable

            - name: Build
              run: cargo build --verbose --all-features --package ${{ matrix.package}}
            
            - name: Test
              run: cargo test --verbose --all-features --package ${{ matrix.package}}

            - name: Check docs
              run: cargo doc --verbose --all-features --package ${{ matrix.package}}

            - name: Try to run
              if: matrix.package == 'dotagrid-cli'
              run: cargo run --verbose --all-features --package ${{ matrix.package}} -- help
