on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  build:
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - name: Get version
        id: get_version
        run: echo "version=$(cargo pkgid | sed 's/.*#//')" >> $GITHUB_OUTPUT

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: cargo build --release --all-features --package dotagrid-cli

      - name: Create release archive
        shell: bash
        run: |
          mkdir release
          cp target/release/dotagrid-cli release/
          cp "$(command -v ffmpeg)" release/
          tar -czvf release.tar.gz release

      - uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.os }}-${{ steps.get_version.outputs.version }}
          path: release.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - name: Get version
        id: get_version
        run: echo "version=$(cargo pkgid | sed 's/.*#//')" >> $GITHUB_OUTPUT

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: release-*-${{ steps.get_version.outputs.version }}
          path: artifacts
          merge-multiple: false

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            # Release v${{ steps.get_version.outputs.version }}
            ## Download the latest release from the [Releases](https://github.com/r41ngee/dota-hero-grid/releases/latest).
          files: artifacts/*/release.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
